src/Entity/Employee.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EmployeeRepository")
 */
class Employee
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $employee_id;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $last_name;

 /**
     * @ORM\Column(type="string", length=50)
     */
    private $gender;

    /**
     * @ORM\Column(type="text")
     */
    private $image_url;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $phone_no;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $type;

    /**
     * @ORM\Column(type="datetime")
     */
    private $registered_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmployeeId(): ?string
    {
        return $this->employee_id;
    }

    public function setEmployeeId(string $employee_id): self
    {
        $this->employee_id = $employee_id;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }


    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getImageUrl(): ?string
    {
        return $this->image_url;
    }

    public function setImageUrl(string $image_url): self
    {
        $this->image_url = $image_url;

        return $this;
    }

    public function getPhoneNo(): ?string
    {
        return $this->phone_no;
    }

    public function setPhoneNo(?string $phone_no): self
    {
        $this->phone_no = $phone_no;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getRegisteredAt(): ?\DateTimeInterface
    {
        return $this->registered_at;
    }

    public function setRegisteredAt(\DateTimeInterface $registered_at): self
    {
        $this->registered_at = $registered_at;

        return $this;
    }
}

templates/authorized/authorized.html.twig
  {% extends "base.admin.twig" %}

  {% block title %}
    <h3 class="text-info">Welcome Page</h3>
{% endblock %}
 

{% block backzone %}
    
{% endblock %}
 {% block body %}

<div class="row">
<div class="col-md-8">
 <div class="jumbotron">
  <h1 class="display-3">Home</h1>
<h2> ለፍተሻ ይተባበሩ</h2>
  <hr class="my-2">

<p> welcome to  Gate Control management system </p>

<p> only authorized users are allowed to get in. any violation ends with hard case...</p>

</div>
</div>
<div class="col-md-4">
 <div class="jumbotron">
  <h1 class="display-3">Home</h1>

  <hr class="my-2">
  <img src="{{asset('images/julogo.jpg')}}" class="img-responsive " width="300" height="300" alt="ju"/>
    <p class="lead">
    <a class="btn btn-primary btn-lg" href="#" role="button">View More</a>
  </p>
</div>
</div>
</div>


     
 {% endblock %}

templates/authorized/displayEmployee.html.twig
{% extends "base.admin.twig" %}

{% block title %}
    <h3 class="text-info">Display Employees  ({{employees|length}})</h3>
{% endblock %}

{% block body %}
   

    <div class="responsive-table">
    <table class="table table-bordered table-condensed dataTable">
    <thead class="bg-info">
    <tr>
    <th>RNo</th>
    <th>Id No</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Phone No</th>
    <th>Occupation</th>
    <th>Date Registered</th>
    <th>Action</th>

    </tr>
    </thead>
<tbody>
   
    {% set i=1 %}
    {% for customer in employees %}


<tr>
<td>
{{ i }}
</td>
<td>
{{ customer.employeeId }}
</td>
<td>
{{customer.firstName}}
</td>
<td>
{{customer.lastName}}
</td>
<td>
{{customer.gender}}
</td>

<td>
{{customer.phoneNo}}
</td>

<td>
{{customer.registeredAt|date("Y-m-d")}}
</td>
<td>
X
</td>

</tr>
{% set i=i+1 %}
{% endfor %}
</tbody>
    </table>

     
    </div>
 


{% endblock %}

templates/authorized/index.twig
{% extends "base.admin.twig" %}

{% block stylesheets %}
{{ parent() }}

<style>
.full_name{
    text-transform:UpperCase;
}
</style>
    
{% endblock %}


{% block myheader %}
<div class=" h1">
<div class="show-time" stlye="padding:100px" ></div>  
</div>  
{% endblock %}


{% block navigation %}

   <a href="{{ path('admin_index') }}" class="btn btn-danger pull-right">Back| {{ users_name }}</a>
{% endblock %}


{% block body %}
  <div class="row">
<div class="col-md-12">

 <div class="form-group form-inline">
    <label for="search_form_user_id">User Id:</label>
    <input type="text"  class=" form-control" id="search_form_user_id" name="search_form_user_id"/>
    <input type="submit" class="btn btn-primary  form-control" id="search_form_search" name="search_form_search"/>
 </div>
 
 
</div>
<div class="col-md-4">
<li class="list-group-item list-group-item-info h4 ">Full Name:   <span class="full_name">Abel Debebe</span></li>
<img src="{{ asset('images/defaultuser.png')}}" class="img-responsive img-thumbnail user_image" alt="user" width="400" height="400"/>
<hr>

<button type="button" class="btn btn-primary col-md-3 btn-report">Report</button>

</div>
<div class="col-md-8">
<div class="table-responsive">
<table class="table table-primary ">
    <thead>
        <tr class="check-status alert">
            <th colspan="2" class="elligible"> Elligible</th>
            
        </tr>
    </thead>
    <tbody>
        <tr>
              <tr>
            <td >IDNo</td>
            <td class="employee_id">Ru 0000/00</td>
            </tr>
        </tr>
            <td>Full Name</td>
            <td class="full_name">Unknown Unknown</td>
        </tr>
        <tr>
            <td >Gender</td>
            <td class="gender">Unknown</td>
        </tr>
        <tr>
            
            <td >Occupation</td>
            <td class="occupation">Unknown</td>
        </tr>
        <tr>
            <td >Last Seen</td>
            <td class="last_seen">00-00-0000</td>
        </tr>
        <tr>
            <td>Phone</td>
            <td class="phone">0000000000000</td>
        </tr>
        <tr>
            <td>Issue</td>
            <td class="issue">Unknown</td>
        </tr>
        <tr>
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>

<div class="panel panel-info">
  <div class="panel-heading">Issues Desription</div>
  <div class="panel-body issue_text">
  some issues in these area  unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passa
  
  
  </div>
</div>
</div>





</div>
    <!-- report modal-->

<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">


    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Report the Issues</h4>
      </div>
      <div class="modal-body">


      <form action="{{ path('search') }}" method="post" >
        <div class="form-group">
  <label for="issue">Issue:</label>
  <textarea class="form-control   report_textarea" rows="5" id="issue"></textarea>
</div>

</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-send-report"  >Report</button>
      </div>
    </div>

  </div>
</div>


{% endblock %}


{% block javascripts %}

{{ parent()}}


<script>



var a;
//window.addEventListener('load', init, false);







$(function(){

     a = new AudioContext();
    document.getElementById("search_form_user_id").focus();

   $('.btn-report').click(function(){

       $('#myModal').modal();
   });
 
 setInterval('showDateTime()',1000);
});


function showDateTime(){
var today = new Date();
var time = today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds();
    $('.show-time').text(time);
}


function init(freq) {
 

  v=a.createOscillator()
  u=a.createGain()
  v.connect(u)
  v.frequency.value=freq
  v.type="square"
  u.connect(a.destination)
  u.gain.value=100*0.01
  v.start(a.currentTime)
  v.stop(a.currentTime+350*0.001)

  


     a.resume().then(() => {
    console.log('Playback resumed successfully');
  });
 
}



$('#search_form_user_id').keypress(function(event){
	
	var keycode = (event.keyCode ? event.keyCode : event.which);
	if(keycode == '13'){
	take_action();
	}

});








 
  $("#search_form_search").click(function(){

take_action();

    });


function take_action(){
var id=$('#search_form_user_id').val();
   if(id==''){
      alert('please enter id no');
   }
   else{
  $.get("{{ path('fetch_user')}}?id="+id,
 
  function(data, status){
if(data=='1'){
    alert("No Such IDNo")
}
else{
var response=data.split('**');
   $('.employee_id').html(response[0]),
   $('.full_name').html(response[1]+" "+response[2]),
   $('.phone').html(response[4]),
   $('.occupation').html(response[5]),
   $('.last_seen').html(response[6]),
   $('.gender').html(response[7]);


   if(response[8]!='0'){

   $('.issue_text').html(response[8])
 



   }

   if(response[9]==0){
  $('.check-status').removeClass('alert-success').addClass("alert-danger");
  $('.elligible').text('Not Elligible');
  init(200);
   }
   else if(response[9]==1){
$('.check-status').removeClass('alert-danger').addClass("alert-success");
$('.elligible').text('Elligible');
init(600);

   }
   else{
       $('.check-status').addClass("alert-warning");
       init(600);
   }

   $('.user_image').attr('src',"{{ asset('images/')}}"+response[3]+"")
   



   // call the audio contenxt
//init();
}

 $('#search_form_user_id').val(""),
  document.getElementById("search_form_user_id").focus();
 
  });

   }
  }
     



// to report issues
  $(".btn-send-report").click(function(){
//alert('erterte');

var employee_id=$('.employee_id').text();
var report_text=$('.report_textarea').val();
 
  $.get("{{ path('report_issue')}}?employee_id="+employee_id+"&data="+report_text,
 
  function(data, status){
if(data=='1'){
    alert("No Such IDNo"),
    $('#myModal').modal("close");
}
else{
    alert("done");
//var response=data.split(',');
   
$('#myModal').modal("hide");

   

}
 $('.report_textarea').val("");
 

  });


  });



</script>



{% endblock %}