src/Entity/Users.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UsersRepository")
 */
class Users
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $idno;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="datetime")
     */
    private $registered_date;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $full_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $profile_pic;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdno(): ?string
    {
        return $this->idno;
    }

    public function setIdno(string $idno): self
    {
        $this->idno = $idno;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getRegisteredDate(): ?\DateTimeInterface
    {
        return $this->registered_date;
    }

    public function setRegisteredDate(\DateTimeInterface $registered_date): self
    {
        $this->registered_date = $registered_date;

        return $this;
    }

    public function getFullName(): ?string
    {
        return $this->full_name;
    }

    public function setFullName(string $full_name): self
    {
        $this->full_name = $full_name;

        return $this;
    }

    public function getProfilePic(): ?string
    {
        return $this->profile_pic;
    }

    public function setProfilePic(?string $profile_pic): self
    {
        $this->profile_pic = $profile_pic;

        return $this;
    }
}

templates/pages/aboutus.twig
{% extends "base.html.twig" %}


{% block title %}
    <h3 class="text-info">About us Page</h3>
{% endblock %}


{% block body %}

 
  
{% endblock %}

templates/pages/admin.html.twig
  {% extends "base.html.twig" %}

  {% block title %}
    <h3 class="text-info">Welcome Page</h3>
{% endblock %}
 

{% block backzone %}
    
{% endblock %}
 {% block body %}

<div class="row">
<div class="col-md-8">
 <div class="jumbotron">
  <h1 class="display-3">Home</h1>
  <p class="lead">Welcome</p>
  <hr class="my-2">
   <p>Jimma University was founded on the amalgamation of the the Jimma Institute of Health Science and 
   the Jimma College of Agriculture in the 1980’s. Both institutions had been national leaders in their 
   respective fields, and with the merger, the development of a new, multifaceted and development oriented
    institution was able to emerge from the two former specialty institutions. Throughout the 1990’s 
    Ethiopia as a nation was determined to overcome the significant development challenges facing the
     country. Such challenges were found in all sectors of society and in all regions.
      Given this reality, new institutions needed to be developed in a manner that would be 
      conducive to the development of the nation. </p>
  
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="https://www.ju.edu.et" role="button">View More</a>
  </p>
</div>
</div>
<div class="col-md-4">
 <div class="jumbotron">
  <h2 class="display-3">Jimma University</h2>
 
  <hr class="my-2">
 <img src="{{asset('images/julogo.jpg')}}" class="img-responsive " width="300" height="300" alt="ju"/>
  
  
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="https://www.ju.edu.et" role="button">View More</a>
  </p>
</div>
</div>
</div>

 <h1 class="jumbotron">
 
 Welcome to Gate Control Management system

 
 </h1>
     
 {% endblock %}

templates/pages/display.twig
{% extends "base.html.twig" %}

{% block title %}
    <h3 class="text-info">Display Customers  ({{customers|length}})</h3>
{% endblock %}

{% block body %}
   

    <div class="responsive-table">
    <table class="table table-bordered table-condensed">
    <thead class="bg-info">
    <tr>
    <th>RNo</th>
    <th>Name</th>
    <th>Account</th>
    <th>Date Registered</th>
    <th>Action</th>

    </tr>
    </thead>
<tbody>
   
    {% set i=1 %}
    {% for customer in customers %}




<tr>
<td>
{{ i }}
</td>
<td>
{{customer.name}}
</td>
<td>
{{customer.accountNo}}
</td>
<td>
{{customer.registeredDate|date("Y-m-d")}}
</td>
<td>
X
</td>

</tr>
{% set i=i+1 %}
{% endfor %}
</tbody>
    </table>

     
    </div>
 


{% endblock %}

templates/pages/register.twig
{% extends "base.html.twig" %}

{% block title %}
    <h3 class="text-info">Register Customers</h3>
{% endblock %}

{% block body %}
   
   <h1 class="text-primary">Form there</h1>
{{ form_start(form)}}   
{{ form_widget(form)}}   
{{ form_end(form)}}   

{% endblock %}

templates/pages/registering.twig
{% extends "base.html.twig" %}


{% block title %}
    <h3 class="text-info">Register Customers</h3>
{% endblock %}

{% block body %}

<div class="row">
<div class="col-md-3">
</div>
<div class="col-md-6">
    <div class="panel panel-primary">
  <div class="panel-heading"> Register user</div>
  <div class="panel-body">
  

{{ form_start(form)}}
{{ form_widget(form)}}

<button type="submit" class="btn btn-primary">Register</button>
{{ form_end(form)}}
  
  </div>
</div>


</div>    
</div>    
{% endblock %}